language: node_js
node_js:
  - lts/*

install:
 - yarn install

services:
  - postgresql

before_script:
  - psql -c 'create database meal-order-test;'

scripts: yarn test

script:
  - nyc --reporter=lcov yarn test

after_script:
  - npm run coverage
